# Generated by Django 5.2 on 2025-06-15 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubjectEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("hours_studied", models.FloatField(default=0)),
                ("previous_scores", models.FloatField(default=50)),
                (
                    "extracurricular",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        max_length=10,
                    ),
                ),
                ("sleep_hours", models.FloatField(default=8)),
                ("question_papers", models.IntegerField(default=0)),
                ("motivation", models.CharField(default="Medium", max_length=255)),
                ("feedback", models.TextField(default="None")),
                ("study_plan", models.TextField(blank=True, null=True)),
                ("predicted_score", models.FloatField(blank=True, null=True)),
                ("study_guide", models.TextField(blank=True, null=True)),
                (
                    "study_plan_pdf",
                    models.FileField(blank=True, null=True, upload_to="study_plans/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.student"
                    ),
                ),
            ],
        ),
    ]
