# Generated by Django 5.2 on 2025-06-27 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subjectentry",
            name="study_plan",
        ),
        migrations.RemoveField(
            model_name="subjectentry",
            name="subject",
        ),
        migrations.AlterField(
            model_name="subjectentry",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_entries",
                to="polls.student",
            ),
        ),
    ]
