# Generated by Django 5.2 on 2025-07-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_remove_subjectentry_study_plan_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subjectentry",
            old_name="feedback",
            new_name="preferred_learning_style",
        ),
    ]
