# Generated by Django 5.2 on 2025-07-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_rename_feedback_subjectentry_preferred_learning_style"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subjectentry",
            unique_together={("student", "subject_name")},
        ),
    ]
