# Generated by Django 5.2 on 2025-08-23 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_alter_subjectentry_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSpecificEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours_studied", models.FloatField(default=0)),
                ("previous_scores", models.FloatField(default=50)),
                (
                    "extracurricular",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        max_length=10,
                    ),
                ),
                ("sleep_hours", models.FloatField(default=8)),
                ("question_papers", models.IntegerField(default=0)),
                ("motivation", models.CharField(default="Medium", max_length=255)),
                ("preferred_learning_style", models.TextField(default="None")),
                ("predicted_score", models.FloatField(blank=True, null=True)),
                ("study_guide", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="polls.subjectentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudyPlanQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subjects", models.CharField(max_length=255)),
                ("learning_style", models.CharField(max_length=50)),
                ("goal", models.CharField(max_length=100)),
                ("hours_per_week", models.IntegerField()),
                ("hours_studied", models.IntegerField(default=0)),
                ("sleep_hours", models.IntegerField(default=0)),
                ("extracurricular", models.IntegerField(default=0)),
                ("question_papers_solved", models.IntegerField(default=0)),
                ("study_habits", models.TextField(blank=True, default="")),
                ("previous_grades", models.IntegerField(default=0)),
                ("motivation_level", models.CharField(default="medium", max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
